# Generated by Django 4.2.5 on 2023-09-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_is_host_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='Room', max_length=20),
        ),
    ]
